### ISSUE TITLE
Broken / missing clickable links

### ISSUE THREAD

**Issue by gendelbendel** [emeria/cheatsheet_monster#1]
The following items are either broken links or could(/should) be clickable links:

Not clickable (suggestions):
- Cheat sheet -> Betrayal reddit link 
- Cheat sheet -> Flask reddit link 
- Thanks -> reddit user MysticReddit should link (similar to page header linking to yours)

Broken (non-functional):
- Misc. -> Data Resources -> PathOfMatth's 
- Feedback -> reddit _thread_ 
- Feedback -> new github issue 
- Feedback -> Readme

**Comment by emeria** [comment]
Thanks, I threw this together pretty quick while making dinner, appreciate the help!

Fixed the feedback bugs, testing a fix for the PoM link.

Added the link to mysticreddit and I changed the sources for image to a link. I am going to try and make a zoom for the images, to enlarge them on click.
